trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'SUA-CONEXAO-AZURE'
  appName: 'cloud-cultura-app'

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'

    - script: npm install
      displayName: 'Instalar dependências'

    - script: echo "Build concluído"
      displayName: 'Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'

    - publish: $(Build.ArtifactStagingDirectory)/app.zip
      artifact: drop

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployWeb
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              package: $(Pipeline.Workspace)/drop/app.zip
